# Generated by Django 5.2.7 on 2025-12-28 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carwash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_minutes",
            field=models.IntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(480),
                ],
                verbose_name="Длительность (минут)",
            ),
        ),
    ]
